Add page allocator AND implement paging
ks0n/goOSe pull request #83
Opened 2021-11-24 08:37 UTC by n1tram1

2021-11-24 08:41 UTC, CohenArthur approved these changes

2021-11-24 09:56 UTC, Skallwar requested changes
There are some some duplication between `src/arch/riscv64/sv39.rs` and `src/mm/mod.rs`

2021-11-24 09:56 UTC, Skallwar commented on src/main.rs
> +    // mm::load_pt(pt);
Dead code ?

2021-11-24 09:56 UTC, Skallwar commented on src/mm/mod.rs
> +// use crate::arch::ArchitectureMemory;
Dead code ?

2021-12-03 22:51 UTC, Skallwar approved these changes

2021-12-03 22:57 UTC, merged