Split interrupts
ks0n/goOSe pull request #84
Opened 2021-12-11 12:24 UTC by Skallwar

Split architecture interrupt handling from base `Architecture` trait and adds a `InterruptsManager`

Names are quite bad, feel free to propose other names the traits, struct fields and variables

2022-01-04 17:54 UTC, n1tram1 requested changes

2022-01-04 17:54 UTC, n1tram1 commented on src/interrupt_manager/mod.rs
> +pub struct InterrupManager<T: arch::ArchitectureInterrupts> {
Typo, `InterrupManager` -> `InterruptManager`

2022-01-06 11:12 UTC, n1tram1 approved these changes

2022-01-06 11:13 UTC, CohenArthur approved these changes

2022-01-06 13:34 UTC, merged