Elf loading
ks0n/goOSe pull request #90
Opened 2022-02-07 17:02 UTC by Skallwar

This PR aims to add elf loading support. This way the kernel would become  "useful".

2022-02-08 08:44 UTC, CohenArthur approved these changes
Looking forward to testing it! :D Nice job!

2022-02-08 08:44 UTC, CohenArthur commented on src/executable/elf.rs
> +                    dst[i as usize] = 0u8;
```suggestion
                for i in p_filesz..p_memsz {
                    dst[i] = 0u8;
```

2022-03-16 23:07 UTC, Skallwar commented
I will create a real test instead of loading from main and we should be good 2 go

2022-03-20 11:22 UTC, CohenArthur commented on src/arch/mod.rs
> +            // We will never use this, we just need the compiler to happy
```suggestion
            // We will never use this, we just need the compiler to be happy
```

2022-03-20 19:42 UTC, Skallwar commented on src/executable/elf.rs
> +                    dst[i as usize] = 0u8;
Fixed, thanks

2022-03-20 19:44 UTC, Skallwar commented on src/arch/mod.rs
> +            // We will never use this, we just need the compiler to happy
Fixed

2022-04-07 20:35 UTC, CohenArthur approved these changes
LGTM :fire: :fire:

2022-04-14 16:50 UTC, n1tram1 approved these changes
smile/dummy_elf: shouldn't we not push the binaries and instead provide a makefile to build them ?

Great work on test cases, we can only be going to the moon now 🚀

Finally some elfs 👺

2022-04-14 16:50 UTC, n1tram1 commented on src/executable/elf.rs
> +    #[test_case]
A test case, now that's a banger 🔥

2022-04-22 21:48 UTC, CohenArthur approved these changes
Me gusta tu Pull Request

2022-04-26 22:01 UTC, n1tram1 requested changes

2022-04-26 22:05 UTC, Skallwar commented on fixtures/Makefile
> +TARGET = $(shell cat ../.cargo/config | awk '/target =/ { print substr($$3, 2, length($$3) - 2) }')
Fixed by dee63f3

2022-04-27 07:48 UTC, CohenArthur approved these changes

2022-05-02 09:37 UTC, CohenArthur approved these changes

2022-05-07 15:13 UTC, merged